export enum AuthRole {

	AUTH_USER_VIEW				= 'AUTH_USER_VIEW',
	AUTH_USER_EDIT				= 'AUTH_USER_EDIT',
	AUTH_USER_MANAGE			= 'AUTH_USER_MANAGE',

	CONSTANT_MANAGE = 'CONSTANT_MANAGE',

	MUSTERI_VIEW	    = 'MUSTERI_VIEW',
	MUSTERI_ADD	    = 'MUSTERI_ADD',
	MUSTERI_EDIT	    = 'MUSTERI_EDIT',
	MUSTERI_DELETE	= 'MUSTERI_DELETE',

	SAAT_VIEW	    = 'SAAT_VIEW',
	SAAT_ADD	    = 'SAAT_ADD',
	SAAT_EDIT	    = 'SAAT_EDIT',
	SAAT_DELETE	= 'SAAT_DELETE',

	MASRAF_VIEW	    = 'MASRAF_VIEW',
	MASRAF_ADD	    = 'MASRAF_ADD',
	MASRAF_EDIT	    = 'MASRAF_EDIT',
	MASRAF_DELETE	= 'MASRAF_DELETE'

}
